///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PlayAgent
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PlayAgentRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    [RepositoryFolder("a8e25e70-4db3-464c-b4ee-21ab079838c5")]
    public partial class PlayAgentRepository : RepoGenBaseFolder
    {
        static PlayAgentRepository instance = new PlayAgentRepository();
        PlayAgentRepositoryFolders.BlankPageAppFolder _blankpage;
        PlayAgentRepositoryFolders.WwwCutvComAppFolder _wwwcutvcom;
        PlayAgentRepositoryFolders.HttpWwwCutvComDemoLiveTestSwfAppFolder _httpwwwcutvcomdemolivetestswf;
        PlayAgentRepositoryFolders.HttpLocalhostLiveTestSwfAppFolder1 _httplocalhostlivetestswf;
        PlayAgentRepositoryFolders.HttpLocalhost9000PublicPlayerLiveAppFolder1 _httplocalhost9000publicplayerlive;

        /// <summary>
        /// Gets the singleton class instance representing the PlayAgentRepository element repository.
        /// </summary>
        [RepositoryFolder("a8e25e70-4db3-464c-b4ee-21ab079838c5")]
        public static PlayAgentRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PlayAgentRepository() 
            : base("PlayAgentRepository", "/", null, 0, false, "a8e25e70-4db3-464c-b4ee-21ab079838c5", ".\\RepositoryImages\\PlayAgentRepositorya8e25e70.rximgres")
        {
            _blankpage = new PlayAgentRepositoryFolders.BlankPageAppFolder(this);
            _wwwcutvcom = new PlayAgentRepositoryFolders.WwwCutvComAppFolder(this);
            _httpwwwcutvcomdemolivetestswf = new PlayAgentRepositoryFolders.HttpWwwCutvComDemoLiveTestSwfAppFolder(this);
            _httplocalhostlivetestswf = new PlayAgentRepositoryFolders.HttpLocalhostLiveTestSwfAppFolder1(this);
            _httplocalhost9000publicplayerlive = new PlayAgentRepositoryFolders.HttpLocalhost9000PublicPlayerLiveAppFolder1(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a8e25e70-4db3-464c-b4ee-21ab079838c5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The BlankPage folder.
        /// </summary>
        [RepositoryFolder("a90bbccc-15d4-4680-b18d-9e75604beb7c")]
        public virtual PlayAgentRepositoryFolders.BlankPageAppFolder BlankPage
        {
            get { return _blankpage; }
        }

        /// <summary>
        /// The WwwCutvCom folder.
        /// </summary>
        [RepositoryFolder("db27b99b-bdf7-4825-8498-c5b713e31871")]
        public virtual PlayAgentRepositoryFolders.WwwCutvComAppFolder WwwCutvCom
        {
            get { return _wwwcutvcom; }
        }

        /// <summary>
        /// The HttpWwwCutvComDemoLiveTestSwf folder.
        /// </summary>
        [RepositoryFolder("4decb25a-8eb6-4d82-a90a-7c8d62f1fb93")]
        public virtual PlayAgentRepositoryFolders.HttpWwwCutvComDemoLiveTestSwfAppFolder HttpWwwCutvComDemoLiveTestSwf
        {
            get { return _httpwwwcutvcomdemolivetestswf; }
        }

        /// <summary>
        /// The HttpLocalhostLiveTestSwf folder.
        /// </summary>
        [RepositoryFolder("d4e347e3-f56d-497d-8c73-3c2de90796be")]
        public virtual PlayAgentRepositoryFolders.HttpLocalhostLiveTestSwfAppFolder1 HttpLocalhostLiveTestSwf
        {
            get { return _httplocalhostlivetestswf; }
        }

        /// <summary>
        /// The HttpLocalhost9000PublicPlayerLive folder.
        /// </summary>
        [RepositoryFolder("38d1340f-cdc3-4b96-bf0e-49f79517ce42")]
        public virtual PlayAgentRepositoryFolders.HttpLocalhost9000PublicPlayerLiveAppFolder1 HttpLocalhost9000PublicPlayerLive
        {
            get { return _httplocalhost9000publicplayerlive; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    public partial class PlayAgentRepositoryFolders
    {
        /// <summary>
        /// The BlankPageAppFolder folder.
        /// </summary>
        [RepositoryFolder("a90bbccc-15d4-4680-b18d-9e75604beb7c")]
        public partial class BlankPageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _livetestswfInfo;

            /// <summary>
            /// Creates a new BlankPage  folder.
            /// </summary>
            public BlankPageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BlankPage", "/form[@title='空白页 - ']", parentFolder, 30000, null, true, "a90bbccc-15d4-4680-b18d-9e75604beb7c", "")
            {
                _livetestswfInfo = new RepoItemInfo(this, "LiveTestSwf", "element[@class='CommandBarClass']//toolbar[@instance='1']/button[@text='live_test.swf']", 30000, null, "8dbe3a21-a4df-4a82-afb0-f9c56087660d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a90bbccc-15d4-4680-b18d-9e75604beb7c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a90bbccc-15d4-4680-b18d-9e75604beb7c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LiveTestSwf item.
            /// </summary>
            [RepositoryItem("8dbe3a21-a4df-4a82-afb0-f9c56087660d")]
            public virtual Ranorex.Button LiveTestSwf
            {
                get
                {
                    return _livetestswfInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LiveTestSwf item info.
            /// </summary>
            [RepositoryItemInfo("8dbe3a21-a4df-4a82-afb0-f9c56087660d")]
            public virtual RepoItemInfo LiveTestSwfInfo
            {
                get
                {
                    return _livetestswfInfo;
                }
            }
        }

        /// <summary>
        /// The WwwCutvComAppFolder folder.
        /// </summary>
        [RepositoryFolder("db27b99b-bdf7-4825-8498-c5b713e31871")]
        public partial class WwwCutvComAppFolder : RepoGenBaseFolder
        {
            PlayAgentRepositoryFolders.HttpLocalhostLiveTestSwfFolder _httplocalhostlivetestswf;
            PlayAgentRepositoryFolders.HttpLocalhost9000PublicPlayerLiveFolder _httplocalhost9000publicplayerlive;
            RepoItemInfo _somebodytagInfo;

            /// <summary>
            /// Creates a new WwwCutvCom  folder.
            /// </summary>
            public WwwCutvComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WwwCutvCom", "/dom[1]", parentFolder, 30000, null, false, "db27b99b-bdf7-4825-8498-c5b713e31871", "")
            {
                _httplocalhostlivetestswf = new PlayAgentRepositoryFolders.HttpLocalhostLiveTestSwfFolder(this);
                _httplocalhost9000publicplayerlive = new PlayAgentRepositoryFolders.HttpLocalhost9000PublicPlayerLiveFolder(this);
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", 30000, null, "b6f3ebdb-93f3-49c2-97e7-f829be0717b7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db27b99b-bdf7-4825-8498-c5b713e31871")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db27b99b-bdf7-4825-8498-c5b713e31871")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("b6f3ebdb-93f3-49c2-97e7-f829be0717b7")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("b6f3ebdb-93f3-49c2-97e7-f829be0717b7")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The HttpLocalhostLiveTestSwf folder.
            /// </summary>
            [RepositoryFolder("3d388c08-38a9-4d9f-9e64-f24c05676722")]
            public virtual PlayAgentRepositoryFolders.HttpLocalhostLiveTestSwfFolder HttpLocalhostLiveTestSwf
            {
                get { return _httplocalhostlivetestswf; }
            }

            /// <summary>
            /// The HttpLocalhost9000PublicPlayerLive folder.
            /// </summary>
            [RepositoryFolder("6e11436d-b3b0-4d98-a469-91a5d82505a9")]
            public virtual PlayAgentRepositoryFolders.HttpLocalhost9000PublicPlayerLiveFolder HttpLocalhost9000PublicPlayerLive
            {
                get { return _httplocalhost9000publicplayerlive; }
            }
        }

        /// <summary>
        /// The HttpLocalhostLiveTestSwfFolder folder.
        /// </summary>
        [RepositoryFolder("3d388c08-38a9-4d9f-9e64-f24c05676722")]
        public partial class HttpLocalhostLiveTestSwfFolder : RepoGenBaseFolder
        {
            RepoItemInfo _停止nInfo;
            RepoItemInfo _播放nInfo;
            RepoItemInfo _rtmptxtInfo;
            RepoItemInfo _firstplaytimenbufferquantitynInfo;
            RepoItemInfo _startandbufferInfo;

            /// <summary>
            /// Creates a new HttpLocalhostLiveTestSwf  folder.
            /// </summary>
            public HttpLocalhostLiveTestSwfFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpLocalhostLiveTestSwf", "?/?/flexobject[@movie='http://localhost/live_test.swf']", parentFolder, 30000, null, false, "3d388c08-38a9-4d9f-9e64-f24c05676722", "")
            {
                _停止nInfo = new RepoItemInfo(this, "停止N", "text[@caption='停止\\n']", 30000, null, "c81b826a-4694-4e91-b6d9-0a3703522f41");
                _播放nInfo = new RepoItemInfo(this, "播放N", "text[@caption='播放\\n']", 30000, null, "71d4d644-2ece-4238-8566-49fffc912ba3");
                _rtmptxtInfo = new RepoItemInfo(this, "RtmpTxt", "text[@displayname='rtmp_txt']", 30000, null, "6a2b7993-c9f0-4c6f-9b0c-3b27fd08f855");
                _firstplaytimenbufferquantitynInfo = new RepoItemInfo(this, "FirstPlayTimeNBufferQuantityN", "text[@caption~'^firstPlayTime:\\\\nBufferQua']", 30000, null, "03dd1fce-8bc5-49b5-9cd8-5b55bf8c58c2");
                _startandbufferInfo = new RepoItemInfo(this, "StartAndBuffer", "text[@displayname='qTxt']", 30000, null, "f5a6c347-ed27-44e8-a0f7-4c94652d0423");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3d388c08-38a9-4d9f-9e64-f24c05676722")]
            public virtual Ranorex.FlexObject Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.FlexObject>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d388c08-38a9-4d9f-9e64-f24c05676722")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 停止N item.
            /// </summary>
            [RepositoryItem("c81b826a-4694-4e91-b6d9-0a3703522f41")]
            public virtual Ranorex.Text 停止N
            {
                get
                {
                    return _停止nInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The 停止N item info.
            /// </summary>
            [RepositoryItemInfo("c81b826a-4694-4e91-b6d9-0a3703522f41")]
            public virtual RepoItemInfo 停止NInfo
            {
                get
                {
                    return _停止nInfo;
                }
            }

            /// <summary>
            /// The 播放N item.
            /// </summary>
            [RepositoryItem("71d4d644-2ece-4238-8566-49fffc912ba3")]
            public virtual Ranorex.Text 播放N
            {
                get
                {
                    return _播放nInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The 播放N item info.
            /// </summary>
            [RepositoryItemInfo("71d4d644-2ece-4238-8566-49fffc912ba3")]
            public virtual RepoItemInfo 播放NInfo
            {
                get
                {
                    return _播放nInfo;
                }
            }

            /// <summary>
            /// The RtmpTxt item.
            /// </summary>
            [RepositoryItem("6a2b7993-c9f0-4c6f-9b0c-3b27fd08f855")]
            public virtual Ranorex.Text RtmpTxt
            {
                get
                {
                    return _rtmptxtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RtmpTxt item info.
            /// </summary>
            [RepositoryItemInfo("6a2b7993-c9f0-4c6f-9b0c-3b27fd08f855")]
            public virtual RepoItemInfo RtmpTxtInfo
            {
                get
                {
                    return _rtmptxtInfo;
                }
            }

            /// <summary>
            /// The FirstPlayTimeNBufferQuantityN item.
            /// </summary>
            [RepositoryItem("03dd1fce-8bc5-49b5-9cd8-5b55bf8c58c2")]
            public virtual Ranorex.Text FirstPlayTimeNBufferQuantityN
            {
                get
                {
                    return _firstplaytimenbufferquantitynInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstPlayTimeNBufferQuantityN item info.
            /// </summary>
            [RepositoryItemInfo("03dd1fce-8bc5-49b5-9cd8-5b55bf8c58c2")]
            public virtual RepoItemInfo FirstPlayTimeNBufferQuantityNInfo
            {
                get
                {
                    return _firstplaytimenbufferquantitynInfo;
                }
            }

            /// <summary>
            /// The StartAndBuffer item.
            /// </summary>
            [RepositoryItem("f5a6c347-ed27-44e8-a0f7-4c94652d0423")]
            public virtual Ranorex.Text StartAndBuffer
            {
                get
                {
                    return _startandbufferInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StartAndBuffer item info.
            /// </summary>
            [RepositoryItemInfo("f5a6c347-ed27-44e8-a0f7-4c94652d0423")]
            public virtual RepoItemInfo StartAndBufferInfo
            {
                get
                {
                    return _startandbufferInfo;
                }
            }
        }

        /// <summary>
        /// The HttpLocalhost9000PublicPlayerLiveFolder folder.
        /// </summary>
        [RepositoryFolder("6e11436d-b3b0-4d98-a469-91a5d82505a9")]
        public partial class HttpLocalhost9000PublicPlayerLiveFolder : RepoGenBaseFolder
        {
            RepoItemInfo _停止nInfo;
            RepoItemInfo _播放nInfo;
            RepoItemInfo _rtmptxtInfo;
            RepoItemInfo _firstplaytimenbufferquantitynInfo;
            RepoItemInfo _startandbufferInfo;

            /// <summary>
            /// Creates a new HttpLocalhost9000PublicPlayerLive  folder.
            /// </summary>
            public HttpLocalhost9000PublicPlayerLiveFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpLocalhost9000PublicPlayerLive", "?/?/flexobject[@movie='http://localhost:9000/public/player/live_test.swf']", parentFolder, 30000, null, false, "6e11436d-b3b0-4d98-a469-91a5d82505a9", "")
            {
                _停止nInfo = new RepoItemInfo(this, "停止N", "text[@caption='停止\\n']", 30000, null, "12667f9a-fd0a-43b3-a6dd-f87613827414");
                _播放nInfo = new RepoItemInfo(this, "播放N", "text[@caption='播放\\n']", 30000, null, "112df601-af1e-470f-9a11-162da8a431d6");
                _rtmptxtInfo = new RepoItemInfo(this, "RtmpTxt", "text[@displayname='rtmp_txt']", 30000, null, "5612e68a-0e46-4e6b-ac03-c5133d7a410a");
                _firstplaytimenbufferquantitynInfo = new RepoItemInfo(this, "FirstPlayTimeNBufferQuantityN", "text[@caption~'^firstPlayTime:\\\\nBufferQua']", 30000, null, "1fec4012-9b99-4bd3-bdef-fc23c342abc6");
                _startandbufferInfo = new RepoItemInfo(this, "StartAndBuffer", "text[@displayname='qTxt']", 30000, null, "1156b00c-3ac3-4207-8c33-5434120e8cd9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6e11436d-b3b0-4d98-a469-91a5d82505a9")]
            public virtual Ranorex.FlexObject Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.FlexObject>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6e11436d-b3b0-4d98-a469-91a5d82505a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 停止N item.
            /// </summary>
            [RepositoryItem("12667f9a-fd0a-43b3-a6dd-f87613827414")]
            public virtual Ranorex.Text 停止N
            {
                get
                {
                    return _停止nInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The 停止N item info.
            /// </summary>
            [RepositoryItemInfo("12667f9a-fd0a-43b3-a6dd-f87613827414")]
            public virtual RepoItemInfo 停止NInfo
            {
                get
                {
                    return _停止nInfo;
                }
            }

            /// <summary>
            /// The 播放N item.
            /// </summary>
            [RepositoryItem("112df601-af1e-470f-9a11-162da8a431d6")]
            public virtual Ranorex.Text 播放N
            {
                get
                {
                    return _播放nInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The 播放N item info.
            /// </summary>
            [RepositoryItemInfo("112df601-af1e-470f-9a11-162da8a431d6")]
            public virtual RepoItemInfo 播放NInfo
            {
                get
                {
                    return _播放nInfo;
                }
            }

            /// <summary>
            /// The RtmpTxt item.
            /// </summary>
            [RepositoryItem("5612e68a-0e46-4e6b-ac03-c5133d7a410a")]
            public virtual Ranorex.Text RtmpTxt
            {
                get
                {
                    return _rtmptxtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RtmpTxt item info.
            /// </summary>
            [RepositoryItemInfo("5612e68a-0e46-4e6b-ac03-c5133d7a410a")]
            public virtual RepoItemInfo RtmpTxtInfo
            {
                get
                {
                    return _rtmptxtInfo;
                }
            }

            /// <summary>
            /// The FirstPlayTimeNBufferQuantityN item.
            /// </summary>
            [RepositoryItem("1fec4012-9b99-4bd3-bdef-fc23c342abc6")]
            public virtual Ranorex.Text FirstPlayTimeNBufferQuantityN
            {
                get
                {
                    return _firstplaytimenbufferquantitynInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstPlayTimeNBufferQuantityN item info.
            /// </summary>
            [RepositoryItemInfo("1fec4012-9b99-4bd3-bdef-fc23c342abc6")]
            public virtual RepoItemInfo FirstPlayTimeNBufferQuantityNInfo
            {
                get
                {
                    return _firstplaytimenbufferquantitynInfo;
                }
            }

            /// <summary>
            /// The StartAndBuffer item.
            /// </summary>
            [RepositoryItem("1156b00c-3ac3-4207-8c33-5434120e8cd9")]
            public virtual Ranorex.Text StartAndBuffer
            {
                get
                {
                    return _startandbufferInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The StartAndBuffer item info.
            /// </summary>
            [RepositoryItemInfo("1156b00c-3ac3-4207-8c33-5434120e8cd9")]
            public virtual RepoItemInfo StartAndBufferInfo
            {
                get
                {
                    return _startandbufferInfo;
                }
            }
        }

        /// <summary>
        /// The HttpWwwCutvComDemoLiveTestSwfAppFolder folder.
        /// </summary>
        [RepositoryFolder("4decb25a-8eb6-4d82-a90a-7c8d62f1fb93")]
        public partial class HttpWwwCutvComDemoLiveTestSwfAppFolder : RepoGenBaseFolder
        {
            PlayAgentRepositoryFolders.选项卡行Folder _选项卡行;
            RepoItemInfo _livetestswfInfo;

            /// <summary>
            /// Creates a new HttpWwwCutvComDemoLiveTestSwf  folder.
            /// </summary>
            public HttpWwwCutvComDemoLiveTestSwfAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpWwwCutvComDemoLiveTestSwf", "/form[@title~'^http://www\\.cutv\\.com/demo/' and @processname='iexplore']", parentFolder, 30000, null, true, "4decb25a-8eb6-4d82-a90a-7c8d62f1fb93", "")
            {
                _选项卡行 = new PlayAgentRepositoryFolders.选项卡行Folder(this);
                _livetestswfInfo = new RepoItemInfo(this, "LiveTestSwf", "element[@class='CommandBarClass']//toolbar[@instance='1']/button[@text='live_test.swf']", 30000, null, "5625b2e0-0e5a-4d5e-8e7c-5335cbe0d4f4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4decb25a-8eb6-4d82-a90a-7c8d62f1fb93")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4decb25a-8eb6-4d82-a90a-7c8d62f1fb93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LiveTestSwf item.
            /// </summary>
            [RepositoryItem("5625b2e0-0e5a-4d5e-8e7c-5335cbe0d4f4")]
            public virtual Ranorex.Button LiveTestSwf
            {
                get
                {
                    return _livetestswfInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LiveTestSwf item info.
            /// </summary>
            [RepositoryItemInfo("5625b2e0-0e5a-4d5e-8e7c-5335cbe0d4f4")]
            public virtual RepoItemInfo LiveTestSwfInfo
            {
                get
                {
                    return _livetestswfInfo;
                }
            }

            /// <summary>
            /// The 选项卡行 folder.
            /// </summary>
            [RepositoryFolder("9dcf22ee-6b10-4c77-8f65-30f04c626b27")]
            public virtual PlayAgentRepositoryFolders.选项卡行Folder 选项卡行
            {
                get { return _选项卡行; }
            }
        }

        /// <summary>
        /// The 选项卡行Folder folder.
        /// </summary>
        [RepositoryFolder("9dcf22ee-6b10-4c77-8f65-30f04c626b27")]
        public partial class 选项卡行Folder : RepoGenBaseFolder
        {
            RepoItemInfo _cutvcomInfo;
            RepoItemInfo _cutvcom1Info;
            RepoItemInfo _cutvcom2Info;

            /// <summary>
            /// Creates a new 选项卡行  folder.
            /// </summary>
            public 选项卡行Folder(RepoGenBaseFolder parentFolder) :
                    base("选项卡行", "element[@class='WorkerW']//tabpagelist[@accessiblename='选项卡行']", parentFolder, 30000, null, false, "9dcf22ee-6b10-4c77-8f65-30f04c626b27", "")
            {
                _cutvcomInfo = new RepoItemInfo(this, "CutvCom", "tabpage[@accessiblerole='PageTab' and @accessibledescription~'^cutv\\.comhttp://www\\.cutv' and @title='cutv.com' and @index='0']", 30000, null, "a42a37b5-9645-42d4-988d-b244500681cd");
                _cutvcom1Info = new RepoItemInfo(this, "CutvCom1", "tabpage[@accessiblerole='PageTab' and @accessibledescription~'^cutv\\.comhttp://www\\.cutv' and @title='cutv.com' and @index='1']", 30000, null, "73022e70-6285-453b-96b4-04bb17b65eef");
                _cutvcom2Info = new RepoItemInfo(this, "CutvCom2", "tabpage[@accessiblerole='PageTab' and @accessibledescription~'^cutv\\.comhttp://www\\.cutv' and @title='cutv.com' and @index='2']", 30000, null, "121bddaf-12a5-437e-b30d-3959fabb202c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9dcf22ee-6b10-4c77-8f65-30f04c626b27")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9dcf22ee-6b10-4c77-8f65-30f04c626b27")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CutvCom item.
            /// </summary>
            [RepositoryItem("a42a37b5-9645-42d4-988d-b244500681cd")]
            public virtual Ranorex.TabPage CutvCom
            {
                get
                {
                    return _cutvcomInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The CutvCom item info.
            /// </summary>
            [RepositoryItemInfo("a42a37b5-9645-42d4-988d-b244500681cd")]
            public virtual RepoItemInfo CutvComInfo
            {
                get
                {
                    return _cutvcomInfo;
                }
            }

            /// <summary>
            /// The CutvCom1 item.
            /// </summary>
            [RepositoryItem("73022e70-6285-453b-96b4-04bb17b65eef")]
            public virtual Ranorex.TabPage CutvCom1
            {
                get
                {
                    return _cutvcom1Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The CutvCom1 item info.
            /// </summary>
            [RepositoryItemInfo("73022e70-6285-453b-96b4-04bb17b65eef")]
            public virtual RepoItemInfo CutvCom1Info
            {
                get
                {
                    return _cutvcom1Info;
                }
            }

            /// <summary>
            /// The CutvCom2 item.
            /// </summary>
            [RepositoryItem("121bddaf-12a5-437e-b30d-3959fabb202c")]
            public virtual Ranorex.TabPage CutvCom2
            {
                get
                {
                    return _cutvcom2Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The CutvCom2 item info.
            /// </summary>
            [RepositoryItemInfo("121bddaf-12a5-437e-b30d-3959fabb202c")]
            public virtual RepoItemInfo CutvCom2Info
            {
                get
                {
                    return _cutvcom2Info;
                }
            }
        }

        /// <summary>
        /// The HttpLocalhostLiveTestSwfAppFolder1 folder.
        /// </summary>
        [RepositoryFolder("d4e347e3-f56d-497d-8c73-3c2de90796be")]
        public partial class HttpLocalhostLiveTestSwfAppFolder1 : RepoGenBaseFolder
        {
            PlayAgentRepositoryFolders.选项卡行Folder1 _选项卡行;

            /// <summary>
            /// Creates a new HttpLocalhostLiveTestSwf  folder.
            /// </summary>
            public HttpLocalhostLiveTestSwfAppFolder1(RepoGenBaseFolder parentFolder) :
                    base("HttpLocalhostLiveTestSwf", "/form[@title~'^http://localhost/live_tes']", parentFolder, 30000, null, true, "d4e347e3-f56d-497d-8c73-3c2de90796be", "")
            {
                _选项卡行 = new PlayAgentRepositoryFolders.选项卡行Folder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d4e347e3-f56d-497d-8c73-3c2de90796be")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4e347e3-f56d-497d-8c73-3c2de90796be")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The 选项卡行 folder.
            /// </summary>
            [RepositoryFolder("489e879b-d8b3-4afb-a432-27289a744167")]
            public virtual PlayAgentRepositoryFolders.选项卡行Folder1 选项卡行
            {
                get { return _选项卡行; }
            }
        }

        /// <summary>
        /// The 选项卡行Folder1 folder.
        /// </summary>
        [RepositoryFolder("489e879b-d8b3-4afb-a432-27289a744167")]
        public partial class 选项卡行Folder1 : RepoGenBaseFolder
        {
            RepoItemInfo _localhostInfo;
            RepoItemInfo _localhost1Info;
            RepoItemInfo _localhost2Info;

            /// <summary>
            /// Creates a new 选项卡行  folder.
            /// </summary>
            public 选项卡行Folder1(RepoGenBaseFolder parentFolder) :
                    base("选项卡行", "element[@class='WorkerW']//tabpagelist[@accessiblename='选项卡行']", parentFolder, 30000, null, false, "489e879b-d8b3-4afb-a432-27289a744167", "")
            {
                _localhostInfo = new RepoItemInfo(this, "Localhost", "tabpage[@accessiblerole='PageTab' and @accessibledescription~'^localhosthttp://localho' and @title='localhost' and @index='0']", 30000, null, "9ead90d5-7170-4bcc-beb7-57e9c191025d");
                _localhost1Info = new RepoItemInfo(this, "Localhost1", "tabpage[@accessiblerole='PageTab' and @accessibledescription~'^localhosthttp://localho' and @title='localhost' and @index='1']", 30000, null, "0c4fc84e-56f6-490e-b7f7-2ec2e85e3b88");
                _localhost2Info = new RepoItemInfo(this, "Localhost2", "tabpage[@accessiblerole='PageTab' and @accessibledescription~'^localhosthttp://localho' and @title='localhost' and @index='2']", 30000, null, "381e90c5-9789-4b48-a251-6955c298d4ba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("489e879b-d8b3-4afb-a432-27289a744167")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("489e879b-d8b3-4afb-a432-27289a744167")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Localhost item.
            /// </summary>
            [RepositoryItem("9ead90d5-7170-4bcc-beb7-57e9c191025d")]
            public virtual Ranorex.TabPage Localhost
            {
                get
                {
                    return _localhostInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Localhost item info.
            /// </summary>
            [RepositoryItemInfo("9ead90d5-7170-4bcc-beb7-57e9c191025d")]
            public virtual RepoItemInfo LocalhostInfo
            {
                get
                {
                    return _localhostInfo;
                }
            }

            /// <summary>
            /// The Localhost1 item.
            /// </summary>
            [RepositoryItem("0c4fc84e-56f6-490e-b7f7-2ec2e85e3b88")]
            public virtual Ranorex.TabPage Localhost1
            {
                get
                {
                    return _localhost1Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Localhost1 item info.
            /// </summary>
            [RepositoryItemInfo("0c4fc84e-56f6-490e-b7f7-2ec2e85e3b88")]
            public virtual RepoItemInfo Localhost1Info
            {
                get
                {
                    return _localhost1Info;
                }
            }

            /// <summary>
            /// The Localhost2 item.
            /// </summary>
            [RepositoryItem("381e90c5-9789-4b48-a251-6955c298d4ba")]
            public virtual Ranorex.TabPage Localhost2
            {
                get
                {
                    return _localhost2Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Localhost2 item info.
            /// </summary>
            [RepositoryItemInfo("381e90c5-9789-4b48-a251-6955c298d4ba")]
            public virtual RepoItemInfo Localhost2Info
            {
                get
                {
                    return _localhost2Info;
                }
            }
        }

        /// <summary>
        /// The HttpLocalhost9000PublicPlayerLiveAppFolder1 folder.
        /// </summary>
        [RepositoryFolder("38d1340f-cdc3-4b96-bf0e-49f79517ce42")]
        public partial class HttpLocalhost9000PublicPlayerLiveAppFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _editInfo;
            RepoItemInfo _clientcaptionInfo;
            RepoItemInfo _localhostInfo;

            /// <summary>
            /// Creates a new HttpLocalhost9000PublicPlayerLive  folder.
            /// </summary>
            public HttpLocalhost9000PublicPlayerLiveAppFolder1(RepoGenBaseFolder parentFolder) :
                    base("HttpLocalhost9000PublicPlayerLive", "/form[@title~'^http://localhost:9000/pub']", parentFolder, 30000, null, true, "38d1340f-cdc3-4b96-bf0e-49f79517ce42", "")
            {
                _editInfo = new RepoItemInfo(this, "Edit", "element[@class='WorkerW']//text[@class='Edit']", 30000, null, "324dd178-046a-4777-bf84-4dc0fb6c5646");
                _clientcaptionInfo = new RepoItemInfo(this, "ClientCaption", "element[@class='Client Caption']", 30000, null, "ca23607b-5a4a-4b29-b170-efbad48f5c58");
                _localhostInfo = new RepoItemInfo(this, "Localhost", "element[@class='WorkerW']//tabpagelist[@accessiblename='选项卡行']/tabpage[@accessiblerole='PageTab' and @accessibledescription~'^localhosthttp://localho' and @title='localhost' and @index='0']", 30000, null, "0472a442-042f-438e-8263-bfac6a6996bf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("38d1340f-cdc3-4b96-bf0e-49f79517ce42")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("38d1340f-cdc3-4b96-bf0e-49f79517ce42")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("324dd178-046a-4777-bf84-4dc0fb6c5646")]
            public virtual Ranorex.Text Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("324dd178-046a-4777-bf84-4dc0fb6c5646")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }

            /// <summary>
            /// The ClientCaption item.
            /// </summary>
            [RepositoryItem("ca23607b-5a4a-4b29-b170-efbad48f5c58")]
            public virtual Ranorex.Unknown ClientCaption
            {
                get
                {
                    return _clientcaptionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClientCaption item info.
            /// </summary>
            [RepositoryItemInfo("ca23607b-5a4a-4b29-b170-efbad48f5c58")]
            public virtual RepoItemInfo ClientCaptionInfo
            {
                get
                {
                    return _clientcaptionInfo;
                }
            }

            /// <summary>
            /// The Localhost item.
            /// </summary>
            [RepositoryItem("0472a442-042f-438e-8263-bfac6a6996bf")]
            public virtual Ranorex.TabPage Localhost
            {
                get
                {
                    return _localhostInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Localhost item info.
            /// </summary>
            [RepositoryItemInfo("0472a442-042f-438e-8263-bfac6a6996bf")]
            public virtual RepoItemInfo LocalhostInfo
            {
                get
                {
                    return _localhostInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}